Repository powerhome/playbook-swift, pull requests merged in 2024-10, with the labels that each got.

#457 [PBIOS-586] Destructive Button
  Sources/Playbook/Components/Button/ButtonsCatalog.swift
  Sources/Playbook/Components/Button/PBButton.swift
  Sources/Playbook/Components/Button/PBButtonVariant.swift
Labels: enhancement, Ready for Testing

#450 [PBIOS-564] Height Adjusted Dropdown
  Sources/Playbook/Components/Typeahead/TypeaheadCatalog.swift
Labels: documentation, Ready for Testing

#454 [PBIOS-541] Message Component Cursor Fix
  Changelog.md
  PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj
  Sources/Playbook/Components/Label Value/LabelValueCatalog.swift
  Sources/Playbook/Components/Message/MessageCatalog.swift
  Sources/Playbook/Components/Message/PBMessage.swift
  project.yml
Labels: improvement, Ready for Testing

#458 [PBIOS-588] User Kit Truncation
  Sources/Playbook/Components/User/PBUser.swift
Labels: improvement, Ready for Testing

#460 [PBIOS-594] User Kit Name Truncation
  Sources/Playbook/Components/User/PBUser.swift
Labels: improvement, Ready for Testing

#456 [PBIOS-583] Add Props To PBMessage
  Sources/Playbook/Components/Message/PBMessage.swift
Labels: Ready for Testing

#464 [PBIOS-611] Turn selected into binding
  Sources/Playbook/Components/Typeahead/PBTypeahead.swift
  Sources/Playbook/Components/Typeahead/TypeaheadCatalog.swift
Labels: Ready for Testing
