Repository powerhome/playbook-swift, pull requests merged in 2024-07, with the labels that each got.

#406 [PBIOS-444] macOS Dialog Kit Catalog Fix
  Package.swift
  Sources/Playbook/Components/Dialog/DialogCatalog.swift
  Sources/Playbook/Components/Dialog/PBDialogActionView.swift
  Sources/Playbook/Components/Dialog/PBStatusDialogView.swift
  Sources/Playbook/Components/User/Multiple Users Indicator/PBMultipleUsersIndicator.swift
Labels: improvement, Ready for Testing

#415 [PBIOS-461]Update Neutral Color
  Sources/Playbook/Components/Pill/PBPill.swift
  Sources/Playbook/Design Elements/Colors/Color.xcassets/Status/Neutral.colorset/Contents.json
Labels: bug, Ready for Testing

#413 [PBIOS-460] Fix user kit name fonts
  Sources/Playbook/Components/Button/PBButton.swift
  Sources/Playbook/Components/Button/PBButtonStyle.swift
  Sources/Playbook/Components/Button/PBButtonVariant.swift
  Sources/Playbook/Components/Button/PBCircleButtonStyle.swift
  Sources/Playbook/Components/User/PBUser.swift
  Sources/Playbook/Components/User/UserCatalog.swift
  Sources/Playbook/Design Elements/Colors/Color.swift
  Sources/Playbook/Design Elements/Typography/Typography.swift
Labels: enhancement, Ready for Testing

#412 [PBIOS-454] Vertical Progress Step Variant
  Package.swift
  Sources/Playbook/Components/Dialog/DialogCatalog.swift
  Sources/Playbook/Components/Dialog/PBDialogActionView.swift
  Sources/Playbook/Components/Dialog/PBStatusDialogView.swift
  Sources/Playbook/Components/Icon/PBIcon.swift
  Sources/Playbook/Components/Progress Step/PBProgressStep.swift
  Sources/Playbook/Components/Progress Step/ProgressStepCatalog.swift
  Sources/Playbook/Components/User/Multiple Users Indicator/PBMultipleUsersIndicator.swift
Labels: enhancement, Ready for Testing

#409 [PBIOS-443] Fixed Confirmation Icon
  Sources/Playbook/Components/Fixed Confirmation Toast/PBToast.swift
  Sources/Playbook/Components/Fixed Confirmation Toast/ToastCatalog.swift
Labels: improvement, Ready for Testing
