Repository powerhome/playbook-swift, pull requests merged in 2024-09, with the labels that each got.

#443 [PBIOS-491] 6.2.0-release
  Changelog.md
  PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj
  project.yml
Labels: Ready for Testing

#442 [PBIOS-508] Reaction Button Dark Mode
  Sources/Playbook/Components/Avatar/PBAvatar.swift
  Sources/Playbook/Components/Button/PBReactionButton.swift
  Sources/Playbook/Design Elements/Colors/Color.swift
  Sources/Playbook/Resources/Extensions/View+ReactionButtonStyle.swift
Labels: improvement, Ready for Testing

#444 [PBIOS-525] PBAvatar status indicator size
  Sources/Playbook/Components/Avatar/AvatarCatalog.swift
  Sources/Playbook/Components/Avatar/PBAvatar.swift
  Sources/Playbook/Components/Online Status/PBOnlineStatus.swift
  Sources/Playbook/Components/User/PBUser.swift
  Sources/Playbook/Resources/Helper Files/Mocks.swift
Labels: improvement, Ready for Testing

#446 [PBIOS-528] Reaction Button Border Dark Mode
  Sources/Playbook/Design Elements/Colors/Color.swift
  Sources/Playbook/Resources/Extensions/View+ReactionButtonStyle.swift
Labels: bug, Ready for Testing

#447 [PBIOS-526] Handle click on message kit
  Sources/Playbook/Components/Dialog/DialogCatalog.swift
  Sources/Playbook/Components/Dialog/PBDialogHeaderView.swift
  Sources/Playbook/Components/Message/MessageCatalog.swift
  Sources/Playbook/Components/Message/PBMessage.swift
  Sources/Playbook/Components/Selectable Card/PBSelectableCard.swift
  Sources/Playbook/Components/Typeahead/GridInputField.swift
  Sources/Playbook/Resources/Extensions/OnHover.swift
  Sources/Playbook/Resources/Extensions/View+DisableAnimation.swift
  Sources/Playbook/Resources/Extensions/View+ReactionButtonStyle.swift
Labels: enhancement, Ready for Testing

#445 [PBIOS-508] Reaction Button Dark Mode
  Sources/Playbook/Components/Button/PBReactionButton.swift
  Sources/Playbook/Components/Typeahead/PBTypeahead.swift
  Sources/Playbook/Design Elements/Colors/Color.swift
  Sources/Playbook/Resources/Extensions/OnHover.swift
  Sources/Playbook/Resources/Extensions/View+ReactionButtonStyle.swift
Labels: bug, Ready for Testing

#449 [PBIOS-566] Fix Online Status Color
  Sources/Playbook/Components/Avatar/AvatarCatalog.swift
  Sources/Playbook/Components/Online Status/PBOnlineStatus.swift
  Sources/Playbook/Resources/Helper Files/Mocks.swift
Labels: bug, Ready for Testing

#452 [PBIOS-529] Improve multiline layout
  Sources/Playbook/Components/Grid/PBGrid.swift
  Sources/Playbook/Components/Typeahead/GridInputField.swift
  Sources/Playbook/Design Elements/Typography/Font+Playbook.swift
Labels: improvement, Ready for Testing
