Repository powerhome/playbook-swift, pull requests merged in 2024-04, with the labels that each got.

#313 [PBIOS-322] Badge Docs
  Sources/Playbook/Components/Badge/docs/_badge_colors_swift.md
  Sources/Playbook/Components/Badge/docs/_badge_default_swift.md
  Sources/Playbook/Components/Badge/docs/_badge_notification_swift.md
  Sources/Playbook/Components/Badge/docs/_badge_props_swift.md
  Sources/Playbook/Components/Badge/docs/_badge_rounded_swift.md
  Sources/Playbook/Components/Badge/docs/example.yml
Labels: documentation, Ready for Testing

#314 [PBIOS-323] Button Docs
  Sources/Playbook/Components/Button/docs/_button_circle_swift.md
  Sources/Playbook/Components/Button/docs/_button_default_swift.md
  Sources/Playbook/Components/Button/docs/_button_full_width_swift.md
  Sources/Playbook/Components/Button/docs/_button_icon_options_swift.md
  Sources/Playbook/Components/Button/docs/_button_props_swift.md
  Sources/Playbook/Components/Button/docs/_button_reaction_swift.md
  Sources/Playbook/Components/Button/docs/_button_size_swift.md
  Sources/Playbook/Components/Button/docs/example.yml
Labels: documentation, Ready for Testing

#315 [PBIOS-324] Card Docs
  Sources/Playbook/Components/Card/docs/_card_background_swift.md
  Sources/Playbook/Components/Card/docs/_card_border_none_swift.md
  Sources/Playbook/Components/Card/docs/_card_border_radius_swift.md
  Sources/Playbook/Components/Card/docs/_card_header_swift.md
  Sources/Playbook/Components/Card/docs/_card_highlight_swift.md
  Sources/Playbook/Components/Card/docs/_card_light_swift.md
  Sources/Playbook/Components/Card/docs/_card_padding_swift.md
  Sources/Playbook/Components/Card/docs/_card_props_swift.md
  Sources/Playbook/Components/Card/docs/_card_separator_swift.md
  Sources/Playbook/Components/Card/docs/_card_shadow_swift.md
  Sources/Playbook/Components/Card/docs/_card_styles_swift.md
  Sources/Playbook/Components/Card/docs/example.yml
Labels: documentation, Ready for Testing

#316 [PBIOS-326] Checkbox Docs
  Sources/Playbook/Components/Checkbox/docs/_checkbox_default_swift.md
  Sources/Playbook/Components/Checkbox/docs/_checkbox_error_swift.md
  Sources/Playbook/Components/Checkbox/docs/_checkbox_indeterminate_swift.md
  Sources/Playbook/Components/Checkbox/docs/_checkbox_props_swift.md
  Sources/Playbook/Components/Checkbox/docs/example.yml
Labels: documentation, Ready for Testing

#312 [PBIOS-315] Date Time Stacked Kit
  Sources/Playbook/Components/Date Time Stacked/DateTimeStackedCatalog.swift
  Sources/Playbook/Components/Date Time Stacked/PBDateTimeStacked.swift
  Sources/Playbook/Components/Date Time Stacked/docs/_date_time_stacked_default_swift.md
  Sources/Playbook/Components/Date Time Stacked/docs/_date_time_stacked_props_swift.md
  Sources/Playbook/Components/Date Time Stacked/docs/example.yml
  Sources/Playbook/Components/Time/PBTime.swift
  Sources/Playbook/Resources/Helper Files/Components.swift
Labels: documentation, enhancement, Ready for Testing

#320 [PBIOS-330] Date Docs
  Sources/Playbook/Components/Date/docs/_ date_unstyled_swift.md
  Sources/Playbook/Components/Date/docs/_date_alignment_swift.md
  Sources/Playbook/Components/Date/docs/_date_default_swift.md
  Sources/Playbook/Components/Date/docs/_date_props_swift.md
  Sources/Playbook/Components/Date/docs/_date_variants_swift.md
  Sources/Playbook/Components/Date/docs/example.yml
Labels: documentation, Ready for Testing

#323 [PBIOS-335] Date Stacked Docs
  Sources/Playbook/Components/Date Stacked/docs/_date_stacked_bold_swift.md
  Sources/Playbook/Components/Date Stacked/docs/_date_stacked_default_swift.md
  Sources/Playbook/Components/Date Stacked/docs/_date_stacked_not_current_year_swift.md
  Sources/Playbook/Components/Date Stacked/docs/_date_stacked_props_swift.md
  Sources/Playbook/Components/Date Stacked/docs/_date_stacked_reversed_swift.md
  Sources/Playbook/Components/Date Stacked/docs/_date_stacked_sizes_swift.md
  Sources/Playbook/Components/Date Stacked/docs/example.yml
Labels: documentation, Ready for Testing

#319 [PBIOS-329] Contact Docs
  Sources/Playbook/Components/Contact/docs/_contact_default_swift.md
  Sources/Playbook/Components/Contact/docs/_contact_props_swift.md
  Sources/Playbook/Components/Contact/docs/_contact_with_detail_swift.md
  Sources/Playbook/Components/Contact/docs/example.yml
Labels: documentation, Ready for Testing

#321 [PBIOS-331] Date Range Inline Docs
  Sources/Playbook/Components/Date Range Inline/docs/_date_range_inline_default_swift.md
  Sources/Playbook/Components/Date Range Inline/docs/_date_range_inline_props_swift.md
  Sources/Playbook/Components/Date Range Inline/docs/example.yml
Labels: documentation, Ready for Testing

#326 [PBIOS-340] Date Year Stacked Docs
  Sources/Playbook/Components/Date Year Stacked/docs/_date_stacked_props_swift:.md
  Sources/Playbook/Components/Date Year Stacked/docs/_date_year_stacked_default_swift.md
  Sources/Playbook/Components/Date Year Stacked/docs/example.yml
Labels: documentation, milano

#327 [PBIOS-43] Loader Kit
  Sources/Playbook/Components/Loader/LoaderCatalog.swift
  Sources/Playbook/Components/Loader/PBLoader.swift
  Sources/Playbook/Design Elements/Iconography/FontAwesome.swift
  Sources/Playbook/Resources/Helper Files/CircularLayout.swift
  Sources/Playbook/Resources/Helper Files/Components.swift
Labels: enhancement, Ready for Testing

#328 [PBIOS-343] Fix fonts line height
  Sources/Playbook/Components/Message/PBMessage.swift
  Sources/Playbook/Design Elements/Typography/Font+Playbook.swift
  Sources/Playbook/Design Elements/Typography/Typography.swift
  Sources/Playbook/Design Elements/Typography/TypographyCatalog.swift
  Sources/Playbook/Resources/Extensions/Font+Message.swift
Labels: improvement, Ready for Testing

#324 [PBIOS-308] Global Positioning Props
  Sources/Playbook/Components/Badge/PBBadge.swift
  Sources/Playbook/Components/Card/CardCatalog.swift
  Sources/Playbook/Components/Card/PBCard.swift
  Sources/Playbook/Components/IconCircle/PBIconCircle.swift
  Sources/Playbook/Components/Message/PBMessage.swift
  Sources/Playbook/Design Elements/Position/GlobalPosition.swift
  Sources/Playbook/Design Elements/Position/GlobalPositionCatalog.swift
  Sources/Playbook/Design Elements/Typography/Typography.swift
  Sources/Playbook/Resources/Helper Files/DesignElements.swift
Labels: enhancement, Ready for Testing

#334 [PBIOS-347] Typography line height validation
  Sources/Playbook/Components/Message/MessageCatalog.swift
  Sources/Playbook/Components/Message/PBMessage.swift
  Sources/Playbook/Components/Time And Date/PBTimestamp.swift
  Sources/Playbook/Design Elements/Typography/Typography.swift
  Sources/Playbook/Design Elements/Typography/TypographyCatalog.swift
  Sources/Playbook/Resources/Helper Files/Components.swift
Labels: Ready for Testing

#332 [PBIOS-312] 4.13.0-release
  PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj
  project.yml
Labels: Ready for Testing

#336 [PBIOS-342] Doc Screenshots
  Sources/Playbook/Components/Currency/docs/_currency_size_swift.md
  Sources/Playbook/Components/Date Range Inline/docs/_date_range_inline_default_swift.md
  Sources/Playbook/Components/Date Range Stacked/docs/_date_range_stacked_default_swift.md
  Sources/Playbook/Components/Date Stacked/docs/_date_stacked_bold_swift.md
  Sources/Playbook/Components/Date Stacked/docs/_date_stacked_default_swift.md
  Sources/Playbook/Components/Date Stacked/docs/_date_stacked_not_current_year_swift.md
  Sources/Playbook/Components/Date Stacked/docs/_date_stacked_reversed_swift.md
  Sources/Playbook/Components/Date Time/docs/_dateTime_alignment_swift.md
  Sources/Playbook/Components/Date Time/docs/_dateTime_default_swift.md
  Sources/Playbook/Components/Date Time/docs/_dateTime_size_swift.md
  Sources/Playbook/Components/Date Year Stacked/docs/_date_year_stacked_default_swift.md
Labels: documentation

#331 [PBIOS-344] Dialog Docs
  Sources/Playbook/Components/Dialog/docs/_dialog_default_swift.md
  Sources/Playbook/Components/Dialog/docs/_dialog_props_swift.md
  Sources/Playbook/Components/Dialog/docs/_dialog_sizes_swift.md
  Sources/Playbook/Components/Dialog/docs/_dialog_stacked_swift.md
  Sources/Playbook/Components/Dialog/docs/_dialog_status_swift.md
  Sources/Playbook/Components/Dialog/docs/example.yml
Labels: documentation

#333 [PBIOS-349] Confirmation Toast Docs
  Sources/Playbook/Components/Fixed Confirmation Toast/docs/_fixed_confirmation_toast_children_swift.md
  Sources/Playbook/Components/Fixed Confirmation Toast/docs/_fixed_confirmation_toast_close_swift.md
  Sources/Playbook/Components/Fixed Confirmation Toast/docs/_fixed_confirmation_toast_default_swift.md
  Sources/Playbook/Components/Fixed Confirmation Toast/docs/_fixed_confirmation_toast_dismiss_with_timer_swift.md
  Sources/Playbook/Components/Fixed Confirmation Toast/docs/_fixed_confirmation_toast_multi_line_swift.md
  Sources/Playbook/Components/Fixed Confirmation Toast/docs/_fixed_confirmation_toast_positions_swift.md
  Sources/Playbook/Components/Fixed Confirmation Toast/docs/_fixed_confirmation_toast_props_swift.md
  Sources/Playbook/Components/Fixed Confirmation Toast/docs/example.yml
Labels: documentation

#335 [PBIOS-341] Message Loading Variant
  Sources/Playbook/Components/Message/MessageCatalog.swift
  Sources/Playbook/Components/Message/PBMessage.swift
  Sources/Playbook/Resources/Helper Files/Mocks.swift
Labels: enhancement, Ready for Testing

#341 [PBIOS-357] Fix Message Loading Timestamp
  Sources/Playbook/Components/Message/MessageCatalog.swift
  Sources/Playbook/Components/Message/PBMessage.swift
Labels: bug, Ready for Testing

#342 [PBIOS-358] 4.14.1-release
  PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj
  project.yml
Labels: bug, Ready for Testing

#337 [PBIOS-303] Typeahead caret indicator
  Sources/Playbook/Components/Fixed Confirmation Toast/PBToast.swift
  Sources/Playbook/Components/Grid/PBGrid.swift
  Sources/Playbook/Components/Popover/PBPopover.swift
  Sources/Playbook/Components/Popover/Popover+Position.swift
  Sources/Playbook/Components/Popover/PopoverCatalog.swift
  Sources/Playbook/Components/Popover/PopoverHandler.swift
  Sources/Playbook/Components/Typeahead/GridInputField.swift
  Sources/Playbook/Components/Typeahead/PBTypeahead.swift
  Sources/Playbook/Components/Typeahead/TypeaheadCatalog.swift
  Sources/Playbook/Design Elements/Typography/TypographyCatalog.swift
  Sources/Playbook/Resources/Extensions/OnChange+Debounce.swift
  Sources/Playbook/Resources/Extensions/View+CancelFirstResponder.swift
  Sources/Playbook/Resources/Extensions/View+Reader.swift
  Sources/Playbook/Resources/Helper Files/Screen.swift
  Sources/Playbook/Resources/Helper Files/ScreenWidth.swift
Labels: Ready for Testing, Product Approved

#343 [PBIOS-359] Add Alignment to Currency
  Sources/Playbook/Components/Currency/CurrencyCatalog.swift
  Sources/Playbook/Components/Currency/PBCurrency.swift
Labels: improvement, Ready for Testing, Product Approved

#339 [PBIOS-287] Button Loading Variant
  Sources/Playbook/Components/Button/ButtonsCatalog.swift
  Sources/Playbook/Components/Button/PBButton.swift
  Sources/Playbook/Components/Button/PBButtonVariant.swift
  Sources/Playbook/Components/Loader/PBLoader.swift
  Sources/Playbook/Components/Message/PBMessage.swift
Labels: enhancement, Ready for Testing, Product Approved

#344 [PBIOS-354] Fix Currency Docs
  Sources/Playbook/Components/Currency/docs/_currency_alignment_swift.md
  Sources/Playbook/Components/Currency/docs/_currency_size_swift.md
Labels: documentation, Ready for Testing, Product Approved, code approved

#345 [PBIOS-353]Update Date Time Stacked Docs
  Sources/Playbook/Components/Date Time Stacked/docs/_date_time_stacked_default_swift.md
Labels: documentation, Ready for Testing, Product Approved, code approved

#346 [PBIOS-345] Dialog Complex Docs
  Sources/Playbook/Components/Dialog/docs/_dialog_complex_swift.md
  Sources/Playbook/Components/Dialog/docs/_dialog_stacked_swift.md
  Sources/Playbook/Components/Dialog/docs/example.yml
Labels: documentation, Ready for Testing, Product Approved, code approved
