Repository powerhome/playbook-swift, pull requests merged in 2024-08, with the labels that each got.

#416 [PBIOS-436] Fix typeahead rendering position for ios
  Sources/Playbook/Components/Popover/Popover+Position.swift
  Sources/Playbook/Components/Popover/PopoverHandler.swift
  Sources/Playbook/Components/Popover/PopoverManager.swift
  Sources/Playbook/Components/Typeahead/PBTypeahead.swift
  Sources/Playbook/Resources/Helper Files/ClickDetectorView.swift
Labels: Ready for Testing

#421 [PBIOS-437] Section Separator Color
  Sources/Playbook/Components/Section Separator/PBSectionSeparator.swift
  Sources/Playbook/Components/Section Separator/SectionSeparatorCatalog.swift
Labels: improvement, Ready for Testing

#411 [PBIOS-453] Progress Step Kit
  Sources/Playbook/Components/Icon/IconCatalog.swift
  Sources/Playbook/Components/Icon/PBIcon.swift
  Sources/Playbook/Components/Progress Pill/PBProgressPill.swift
  Sources/Playbook/Components/Progress Step/PBProgressStep.swift
  Sources/Playbook/Components/Progress Step/ProgressStepCatalog.swift
  Sources/Playbook/Resources/Helper Files/Components.swift
Labels: enhancement, Ready for Testing

#427 [PBIOS-473] macOS Dialog Sizes
  Sources/Playbook/Components/Dialog/DialogCatalog.swift
  Sources/Playbook/Components/Dialog/PBDialog.swift
  Sources/Playbook/Resources/Extensions/View+PresentationMode.swift
Labels: improvement, Ready for Testing

#424 [PBIOS-456] Progress Simple Kit
  Sources/Playbook/Components/Progress Simple/PBProgressSimple.swift
  Sources/Playbook/Components/Progress Simple/ProgressSimpleCatalog.swift
  Sources/Playbook/Design Elements/Colors/Color.xcassets/Text/TextLight.colorset/Contents.json
  Sources/Playbook/Resources/Helper Files/Components.swift
Labels: enhancement, Ready for Testing

#420 [PBIOS-448] Multiple Users Small Bubble Variant
  Sources/Playbook/Components/Avatar/PBAvatar.swift
  Sources/Playbook/Components/User/Multiple Users/MultipleUsersCatalog.swift
  Sources/Playbook/Components/User/Multiple Users/PBMultipleUsers.swift
  Sources/Playbook/Resources/Helper Files/Mocks.swift
Labels: enhancement, Ready for Testing

#431 [PBIOS-467] Typeahead manager fix
  Gemfile.lock
  Sources/Playbook/Components/Popover/PBPopover.swift
  Sources/Playbook/Components/Popover/Popover+Position.swift
  Sources/Playbook/Components/Popover/PopoverCatalog.swift
  Sources/Playbook/Components/Popover/PopoverHandler.swift
  Sources/Playbook/Components/Popover/PopoverManager.swift
  Sources/Playbook/Components/Typeahead/PBTypeahead.swift
  Sources/Playbook/Components/Typeahead/TypeaheadCatalog.swift
  Sources/Playbook/Resources/Helper Files/Mocks.swift
Labels: Ready for Testing

#422 [PBIOS-468] Online Status Kit
  Sources/Playbook/Components/Online Status/OnlineStatusCatalog.swift
  Sources/Playbook/Components/Online Status/PBOnlineStatus.swift
  Sources/Playbook/Resources/Helper Files/Components.swift
Labels: enhancement, Ready for Testing

#433 [PBIOS-466] Multiple User Bubble Sizes
  Sources/Playbook/Components/User/Multiple Users/MultipleUsersCatalog.swift
  Sources/Playbook/Components/User/Multiple Users/PBMultipleUsers.swift
Labels: enhancement, Ready for Testing

#434 [PBIOS-474] Dialog Cursor macOS
  Sources/Playbook/Components/Dialog/PBDialogHeaderView.swift
Labels: bug, Ready for Testing

#435 [PBIOS-469] Full Width Nav
  PlaybookShowcase/PlaybookShowcase/ContentListView.swift
  Sources/Playbook/Components/Nav/NavCatalog.swift
  Sources/Playbook/Components/Nav/PBNav.swift
  Sources/Playbook/Components/Nav/PBNavItem.swift
Labels: improvement, Ready for Testing

#436 [PBIOS-476] Dark Mode Status Avatar Fix
  Sources/Playbook/Components/Avatar/PBAvatar.swift
  Sources/Playbook/Components/Online Status/PBOnlineStatus.swift
  Sources/Playbook/Design Elements/Colors/Color.swift
Labels: improvement, Ready for Testing

#437 [PBIOS-481] Multi User Dark Mode
  Sources/Playbook/Components/User/Multiple Users/PBMultipleUsers.swift
  Sources/Playbook/Design Elements/Colors/Color.swift
Labels: improvement, Ready for Testing

#438 [PBIOS-483] Dark Mode Checkbox Outline Fix
  Sources/Playbook/Components/Checkbox/PBCheckboxStyle.swift
Labels: bug, Ready for Testing

#440 [PBIOS-427] Dark Mode Button Fix
  Sources/Playbook/Components/Button/PBButton.swift
  Sources/Playbook/Components/Button/PBReactionButton.swift
  Sources/Playbook/Resources/Extensions/View+ReactionButtonStyle.swift
Labels: bug, Ready for Testing
