Repository powerhome/playbook-swift, pull requests merged in 2024-01, with the labels that each got.

#231 [PBIOS-247] Add template back to project folder
  .github/PULL_REQUEST_TEMPLATE.md
  PlaybookShowcase/PlaybookShowcase.xcodeproj/project.xcworkspace/xcuserdata/isis.silva.xcuserdatad/UserInterfaceState.xcuserstate
Labels: documentation, Ready for Testing

#232 [PBIOS-92] Tab Bar Kit
  Sources/Playbook/Components/Nav/NavCatalog.swift
  Sources/Playbook/Components/Select/SelectCatalog.swift
  Sources/Playbook/Components/Tab Bar/PBTabBar.swift
  Sources/Playbook/Components/Tab Bar/TabBarCatalog.swift
  Sources/Playbook/Components/Toggle/ToggleCatalog.swift
  Sources/Playbook/Components/User/MultipleUsersCatalog.swift
  Sources/Playbook/Components/User/MultipleUsersIndicatorCatalog.swift
  Sources/Playbook/Components/User/UserCatalog.swift
  Sources/Playbook/Design Elements/Shadows/PBShadow.swift
  Sources/Playbook/Resources/Helper Files/Components.swift
Labels: enhancement, Ready for Testing

#224 [PBIOS-240] Fix Nav kit Messages icon
  PlaybookShowcase/PlaybookShowcase/ContentListView.swift
  Sources/Playbook/Components/Nav/NavCatalog.swift
  Sources/Playbook/Components/Nav/PBNav.swift
  Sources/Playbook/Design Elements/Iconography/FontAwesome.swift
Labels: bug, Ready for Release, Ready for Testing

#221 [PBIOS-234] Release Script
  project.yml
  release.sh
Labels: improvement, Ready for Testing

#235 [PBIOS-251] Fix popover initializer access level
  Sources/Playbook/Components/Popover/PBPopover.swift
Labels: bug, Ready for Testing

#140 [PBIOS-154] New Typeahead kit
  Package.swift
  PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj
  Sources/Playbook/Components/Badge/PBBadge.swift
  Sources/Playbook/Components/Message/MessageCatalog.swift
  Sources/Playbook/Components/Popover/PBPopover.swift
  Sources/Playbook/Components/Popover/PopoverCatalog.swift
  Sources/Playbook/Components/Popover/PopoverHandler.swift
  Sources/Playbook/Components/Text Input/PBTextInput.swift
  Sources/Playbook/Components/Typeahead/PBTypeahead.swift
  Sources/Playbook/Components/Typeahead/Pill/TypeaheadPill.swift
  Sources/Playbook/Components/Typeahead/Pill/TypeaheadPillCatalog.swift
  Sources/Playbook/Components/Typeahead/TypeaheadCatalog.swift
  Sources/Playbook/Components/Typeahead/WrappedInputField.swift
  Sources/Playbook/Components/User/MultipleUsersCatalog.swift
  Sources/Playbook/Components/User/MultipleUsersStacked/MultipleUsersStackedCatalog.swift
  Sources/Playbook/Design Elements/Colors/Colors.xcassets/Hover/Hover.colorset/Contents.json
  Sources/Playbook/Design Elements/Colors/Colors.xcassets/Text/TextLight.colorset/Contents.json
  Sources/Playbook/Design Elements/Iconography/FontAwesome.swift
  Sources/Playbook/Resources/Extensions/Custom+EnvironmentValues.swift
  Sources/Playbook/Resources/Helper Files/Components.swift
  Sources/Playbook/Resources/Helper Files/UserMock.swift
Labels: Ready for Release, Ready for Testing

#268 [PBIOS-254] Release script update
  release.sh
Labels: Ready for Testing

#234 [PBIOS-243] Stacked Dialog and Complex example fix
  Sources/Playbook/Components/Dialog/DialogCatalog.swift
  Sources/Playbook/Components/Dialog/PBDialogActionView.swift
  Sources/Playbook/Components/Dialog/PBStatusDialogView.swift
Labels: bug, enhancement, Ready for Testing

#237 [PBIOS-236] Tool Tip Validation
  Sources/Playbook/Components/Tooltip/PBTooltip.swift
Labels: improvement, Ready for Testing

#269 [PBIOS-237] Add macOS target
  Jenkinsfile
  PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj
  PlaybookShowcase/PlaybookShowcase/Assets.xcassets/AppIcon.appiconset/1024.png
  PlaybookShowcase/PlaybookShowcase/Assets.xcassets/AppIcon.appiconset/128.png
  PlaybookShowcase/PlaybookShowcase/Assets.xcassets/AppIcon.appiconset/16.png
  PlaybookShowcase/PlaybookShowcase/Assets.xcassets/AppIcon.appiconset/256 1.png
  PlaybookShowcase/PlaybookShowcase/Assets.xcassets/AppIcon.appiconset/256.png
  PlaybookShowcase/PlaybookShowcase/Assets.xcassets/AppIcon.appiconset/32 1.png
  PlaybookShowcase/PlaybookShowcase/Assets.xcassets/AppIcon.appiconset/32.png
  PlaybookShowcase/PlaybookShowcase/Assets.xcassets/AppIcon.appiconset/512 1.png
  PlaybookShowcase/PlaybookShowcase/Assets.xcassets/AppIcon.appiconset/512.png
  PlaybookShowcase/PlaybookShowcase/Assets.xcassets/AppIcon.appiconset/64.png
  PlaybookShowcase/PlaybookShowcase/Assets.xcassets/AppIcon.appiconset/Contents.json
  Tools/keychain.sh
  fastlane/Fastfile
Labels: Ready for Testing
