Repository powerhome/playbook-swift, pull requests merged in 2024-02, with the labels that each got.

#272 [PBIOS-267] Add position offset to popover
  Sources/Playbook/Components/Popover/PBPopover.swift
  Sources/Playbook/Components/Popover/PopoverCatalog.swift
Labels: enhancement, Ready for Testing

#276 [PBIOS-145] Fix PBSelect for macOS
  PlaybookSwift.xcworkspace/xcuserdata/rachel.radford.xcuserdatad/UserInterfaceState.xcuserstate
  Sources/Playbook/Components/Select/PBSelect.swift
Labels: bug, milano, Ready for Testing

#277 [PBIOS-264]Update PR template to match Playbook
  .github/PULL_REQUEST_TEMPLATE.md
Labels: improvement, Ready for Testing

#280 [PBIOS-244] User Kit Add Subtitle Prop
  PlaybookSwift.xcworkspace/xcuserdata/rachel.radford.xcuserdatad/UserInterfaceState.xcuserstate
  Sources/Playbook/Components/User/Multiple Users Indicator/MultipleUsersIndicatorCatalog.swift
  Sources/Playbook/Components/User/Multiple Users Indicator/PBMultipleUsersIndicator.swift
  Sources/Playbook/Components/User/Multiple Users Stacked/MultipleUsersStackedCatalog.swift
  Sources/Playbook/Components/User/Multiple Users Stacked/PBMultipleUsersStacked.swift
  Sources/Playbook/Components/User/Multiple Users/MultipleUsersCatalog.swift
  Sources/Playbook/Components/User/Multiple Users/PBMultipleUsers.swift
  Sources/Playbook/Components/User/PBUser.swift
  Sources/Playbook/Components/User/UserCatalog.swift
  Sources/Playbook/Resources/Helper Files/Components.swift
  Sources/Playbook/Resources/Helper Files/Mocks.swift
Labels: enhancement, Ready for Testing

#285 [PBIOS-281] Rename project repo
  Jenkinsfile
  Tools/github-utils.sh
  portal.yml
Labels: Ready for Testing

#267 [PBIOS-248] Improve Typeahead Kit Focus
  Package.swift
  PlaybookShowcase/PlaybookShowcase/PlaybookShowcaseApp.swift
  Sources/Playbook/Components/Typeahead/PBTypeahead.swift
  Sources/Playbook/Components/Typeahead/TypeaheadCatalog.swift
  Sources/Playbook/Components/Typeahead/WrappedInputField.swift
  Sources/Playbook/Resources/Extensions/View+ReactionButtonStyle.swift
Labels: bug, Ready for Testing

#283 [PBIOS-278] NEW Highlight kit
  PlaybookSwift.xcworkspace/xcuserdata/rachel.radford.xcuserdatad/UserInterfaceState.xcuserstate
  Sources/Playbook/Components/Highlight/HighlightCatalog.swift
  Sources/Playbook/Components/Highlight/PBHighlight.swift
  Sources/Playbook/Components/Highlight/docs/_highlight_default_swift.md
  Sources/Playbook/Components/Highlight/docs/_highlight_props_swift.md
  Sources/Playbook/Components/Highlight/docs/example.yml
  Sources/Playbook/Resources/Extensions/View+AttributedString.swift
  Sources/Playbook/Resources/Helper Files/Components.swift
Labels: enhancement, Ready for Testing

#287 [PBIOS-276] Fix select kit
  Sources/Playbook/Components/Select/PBSelect.swift
Labels: Ready for Testing

#281 [PBIOS-275] Time Kit
  PlaybookSwift.xcworkspace/xcuserdata/rachel.radford.xcuserdatad/UserInterfaceState.xcuserstate
  Sources/Playbook/Components/Time/PBTime.swift
  Sources/Playbook/Components/Time/TimeCatalog.swift
  Sources/Playbook/Components/Time/docs/_time_alignment_swift.md
  Sources/Playbook/Components/Time/docs/_time_default_swift.md
  Sources/Playbook/Components/Time/docs/_time_props_swift.md
  Sources/Playbook/Components/Time/docs/_time_sizes_swift.md
  Sources/Playbook/Components/Time/docs/_time_timezone_swift.md
  Sources/Playbook/Components/Time/docs/_time_unstyled_swift.md
  Sources/Playbook/Components/Time/docs/example.yml
  Sources/Playbook/Resources/Helper Files/Components.swift
Labels: enhancement, Ready for Testing

#288 [PBIOS-290] Fix subtitle prop
  Sources/Playbook/Components/User/Multiple Users Stacked/PBMultipleUsersStacked.swift
  Sources/Playbook/Components/User/Multiple Users/PBMultipleUsers.swift
  Sources/Playbook/Components/User/PBUser.swift
  Sources/Playbook/Components/User/UserCatalog.swift
Labels: Ready for Testing
