Repository powerhome/playbook-swift, pull requests merged in 2024-03, with the labels that each got.

#292 [PBIOS-292] Add Presence Indicator to User Kit
  .gitignore
  PlaybookSwift.xcworkspace/xcuserdata/rachel.radford.xcuserdatad/UserInterfaceState.xcuserstate
  Sources/Playbook/Components/User/PBUser.swift
  Sources/Playbook/Components/User/UserCatalog.swift
Labels: enhancement, Ready for Testing

#298 [PBIOS-284] Time Stacked kit
  Sources/Playbook/Components/Time Stacked/PBTimeStacked.swift
  Sources/Playbook/Components/Time Stacked/TimeStackedCatalog.swift
  Sources/Playbook/Components/Time Stacked/docs/_timeStacked_default_swift.md
  Sources/Playbook/Components/Time Stacked/docs/_timeStacked_props_swift.md
  Sources/Playbook/Components/Time Stacked/docs/example.yml
  Sources/Playbook/Components/Time/PBTime.swift
  Sources/Playbook/Resources/Helper Files/Components.swift
Labels: enhancement, Ready for Testing

#293 [PBIOS-291] Currency Kit
  PlaybookSwift.xcworkspace/xcuserdata/rachel.radford.xcuserdatad/UserInterfaceState.xcuserstate
  Sources/Playbook/Components/Currency/CurrencyCatalog.swift
  Sources/Playbook/Components/Currency/PBCurrency.swift
  Sources/Playbook/Components/Currency/docs/_currency_alignment_swift.md
  Sources/Playbook/Components/Currency/docs/_currency_props_swift.md
  Sources/Playbook/Components/Currency/docs/_currency_size_swift.md
  Sources/Playbook/Components/Currency/docs/example.yml
  Sources/Playbook/Resources/Helper Files/Components.swift
Labels: enhancement, Ready for Testing

#297 [PBIOS-283] Time Range Inline kit
  PlaybookSwift.xcworkspace/xcuserdata/rachel.radford.xcuserdatad/UserInterfaceState.xcuserstate
  Sources/Playbook/Components/Time Range Inline/PBTimeRangeInline.swift
  Sources/Playbook/Components/Time Range Inline/TimeRangeInlineCatalog.swift
  Sources/Playbook/Components/Time Range Inline/docs/_timeRangeInline_default_swift.md
  Sources/Playbook/Components/Time Range Inline/docs/_timeRangeInline_props_swift.md
  Sources/Playbook/Components/Time Range Inline/docs/example.yml
  Sources/Playbook/Components/Time/PBTime.swift
  Sources/Playbook/Components/Time/docs/_time_props_swift.md
  Sources/Playbook/Resources/Helper Files/Components.swift
Labels: enhancement, Ready for Testing

#300 [PBIOS-300]RemoveYearFromDateKitWhenCurrent
  Sources/Playbook/Components/Date/DateCatalog.swift
  Sources/Playbook/Components/Date/PBDate.swift
Labels: bug, Ready for Testing

#303 [PBIOS-299] Release 4.12.0
  Changelog.md
  PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj
  project.yml
Labels: Ready for Release, Ready for Testing

#301 [PBIOS-297] Date Time Kit
  Sources/Playbook/Components/Date Time/DateTimeCatalog.swift
  Sources/Playbook/Components/Date Time/PBDateTime.swift
  Sources/Playbook/Components/Date Time/docs/_dateTime_alignment_swift.md
  Sources/Playbook/Components/Date Time/docs/_dateTime_default_swift.md
  Sources/Playbook/Components/Date Time/docs/_dateTime_props_swift.md
  Sources/Playbook/Components/Date Time/docs/_dateTime_size_swift.md
  Sources/Playbook/Components/Date Time/docs/example.yml
  Sources/Playbook/Components/Date/DateCatalog.swift
  Sources/Playbook/Components/Date/PBDate.swift
  Sources/Playbook/Components/Highlight/docs/example.yml
  Sources/Playbook/Components/Time/PBTime.swift
  Sources/Playbook/Components/Time/TimeCatalog.swift
  Sources/Playbook/Resources/Helper Files/Components.swift
Labels: documentation, enhancement, Ready for Testing

#304 [PBIOS-307] Date Range Inline Kit
  Sources/Playbook/Components/Date Range Inline/DateRangeInlineCatalog.swift
  Sources/Playbook/Components/Date Range Inline/PBDateRangeInline.swift
  Sources/Playbook/Components/Date Time/DateTimeCatalog.swift
  Sources/Playbook/Components/Date/DateCatalog.swift
  Sources/Playbook/Components/Date/PBDate.swift
  Sources/Playbook/Resources/Helper Files/Components.swift
Labels: enhancement, Ready for Testing

#305 [PBIOS-310] Date Stacked Kit
  Sources/Playbook/Components/Currency/PBCurrency.swift
  Sources/Playbook/Components/Date Range Inline/PBDateRangeInline.swift
  Sources/Playbook/Components/Date Stacked/DateStackedCatalog.swift
  Sources/Playbook/Components/Date Stacked/PBDateStacked.swift
  Sources/Playbook/Components/Date/PBDate.swift
  Sources/Playbook/Components/Label Value/PBLabelValue.swift
  Sources/Playbook/Components/Time/PBTime.swift
  Sources/Playbook/Resources/Helper Files/Components.swift
Labels: enhancement, Ready for Testing

#309 [PBIOS-318] Fix Date Time Kit Font
  Sources/Playbook/Components/Date Time/DateTimeCatalog.swift
  Sources/Playbook/Components/Date Time/PBDateTime.swift
  Sources/Playbook/Components/Date/PBDate.swift
Labels: bug, Ready for Testing

#299 [PBIOS-249] Refactor typeahead data
  Package.swift
  Sources/Playbook/Components/Grid/GridCatalog.swift
  Sources/Playbook/Components/Grid/PBGrid.swift
  Sources/Playbook/Components/Typeahead/GridInputField.swift
  Sources/Playbook/Components/Typeahead/PBTypeahead.swift
  Sources/Playbook/Components/Typeahead/TypeaheadCatalog.swift
  Sources/Playbook/Resources/Extensions/OnChange+Debounce.swift
  Sources/Playbook/Resources/Helper Files/Components.swift
Labels: improvement, Ready for Testing

#310 [PBIOS-313] Date Range Stacked Kit
  Sources/Playbook/Components/Date Range Stacked/DateRangeStackedCatalog.swift
  Sources/Playbook/Components/Date Range Stacked/PBDateRangeStacked.swift
  Sources/Playbook/Components/Date Year Stacked/PBDateYearStacked.swift
  Sources/Playbook/Resources/Helper Files/Components.swift
Labels: enhancement, Ready for Testing

#311 [PBIOS-320] Avatar Docs
  Sources/Playbook/Components/Avatar/docs/_avatar_default_swift.md
  Sources/Playbook/Components/Avatar/docs/_avatar_monogram_swift.md
  Sources/Playbook/Components/Avatar/docs/_avatar_props_swift.md
  Sources/Playbook/Components/Avatar/docs/example.yml
Labels: documentation, Ready for Testing
