Repository powerhome/playbook-swift, pull requests merged in 2024-06, with the labels that each got.

#383 [PBIOS-403] Selectable Card Input Variant
  Sources/Playbook/Components/Card/PBCard.swift
  Sources/Playbook/Components/Card/PBCardStyle.swift
  Sources/Playbook/Components/Selectable Card/PBSelectableCard.swift
  Sources/Playbook/Components/Selectable Card/SelectableCardCatalog.swift
Labels: improvement, Ready for Testing

#399 [PBIOS-431] Removes Unnecessary Print Statements
  Sources/Playbook/Components/Popover/PopoverCatalog.swift
  Sources/Playbook/Components/Popover/PopoverManager.swift
  Sources/Playbook/Components/Typeahead/TypeaheadCatalog.swift
Labels: bug, Ready for Testing

#391 [PBIOS-397] User Docs
  Sources/Playbook/Components/User/docs/_user_block_content_subtitle_swift.md
  Sources/Playbook/Components/User/docs/_user_horizontal_sizes_swift.md
  Sources/Playbook/Components/User/docs/_user_horizontal_swift.md
  Sources/Playbook/Components/User/docs/_user_presence_indicator_swift.md
  Sources/Playbook/Components/User/docs/_user_props_swift.md
  Sources/Playbook/Components/User/docs/_user_text_only_swift.md
  Sources/Playbook/Components/User/docs/_user_vertical_swift.md
  Sources/Playbook/Components/User/docs/example.yml
Labels: documentation, Ready for Testing, Product Approved

#394 [PBIOS-334] Add swift fonts package to power-fonts
  Gemfile.lock
  Package.swift
  Sources/Playbook/Components/Text Input/PBTextInput.swift
  Sources/Playbook/Components/Typeahead/Pill/TypeaheadPill.swift
  Sources/Playbook/Design Elements/Typography/Font+Playbook.swift
  Sources/Playbook/Resources/Assets/Fonts/ProximaNova-Black.otf
  Sources/Playbook/Resources/Assets/Fonts/ProximaNova-BlackIt.otf
  Sources/Playbook/Resources/Assets/Fonts/ProximaNova-Bold.otf
  Sources/Playbook/Resources/Assets/Fonts/ProximaNova-BoldIt.otf
  Sources/Playbook/Resources/Assets/Fonts/ProximaNova-Extrabld.otf
  Sources/Playbook/Resources/Assets/Fonts/ProximaNova-ExtrabldIt.otf
  Sources/Playbook/Resources/Assets/Fonts/ProximaNova-Light.otf
  Sources/Playbook/Resources/Assets/Fonts/ProximaNova-LightIt.otf
  Sources/Playbook/Resources/Assets/Fonts/ProximaNova-Regular.otf
  Sources/Playbook/Resources/Assets/Fonts/ProximaNova-RegularIt.otf
  Sources/Playbook/Resources/Assets/Fonts/ProximaNova-Semibold.otf
  Sources/Playbook/Resources/Assets/Fonts/ProximaNova-SemiboldIt.otf
  Sources/Playbook/Resources/Assets/Fonts/ProximaNova-Thin.otf
  Sources/Playbook/Resources/Assets/Fonts/ProximaNova-ThinIt.otf
  Sources/Playbook/Resources/Helper Files/Font+ProximaNova.swift
  Sources/Playbook/Resources/Helper Files/Font+Register.swift
  fastlane/Fastfile
Labels: Ready for Testing

#400 [PBIOS-434] Label Pill Kit
  Sources/Playbook/Components/Label Pill/LabelPillCatalog.swift
  Sources/Playbook/Components/Label Pill/PBLabelPill.swift
  Sources/Playbook/Resources/Helper Files/Components.swift
Labels: enhancement, Ready for Testing

#403 [PBIOS-407] Typeahead validation
  Sources/Playbook/Components/Typeahead/GridInputField.swift
  Sources/Playbook/Components/Typeahead/PBTypeahead.swift
  Sources/Playbook/Components/Typeahead/TypeaheadCatalog.swift
  Sources/Playbook/Resources/Helper Files/ClickDetectorView.swift
Labels: improvement, Ready for Testing, Product Approved

#404 [PBIOS-440] Pill Kit Color Validation
  Sources/Playbook/Components/Message/MessageCatalog.swift
  Sources/Playbook/Design Elements/Colors/Color.xcassets/Status/Neutral.colorset/Contents.json
  Sources/Playbook/Design Elements/Colors/Color.xcassets/Status/Warning.colorset/Contents.json
Labels: bug, Ready for Testing, Product Approved

#395 [PBIOS-420] Expose button variants on dialog kit
  Sources/Playbook/Components/Button/ButtonsCatalog.swift
  Sources/Playbook/Components/Button/PBButton.swift
  Sources/Playbook/Components/Dialog/DialogCatalog.swift
  Sources/Playbook/Components/Dialog/PBDialog.swift
  Sources/Playbook/Components/Dialog/PBDialogActionView.swift
Labels: Ready for Testing, Product Approved

#401 [PBIOS-435] Progress Pill Kit
  Sources/Playbook/Components/Progress Pill/PBProgressPill.swift
  Sources/Playbook/Components/Progress Pill/ProgressPillCatalog.swift
  Sources/Playbook/Resources/Helper Files/Components.swift
Labels: enhancement, Ready for Testing

#402 [PBIOS-438] User Kit Spacing Fix
  Sources/Playbook/Components/User/PBUser.swift
  Sources/Playbook/Components/User/UserCatalog.swift
  Sources/Playbook/Resources/Helper Files/PBDocStack.swift
Labels: bug, Ready for Testing, Product Approved

#407 [PBIOS-447] Update Runway comment endpoint
  Package.swift
  fastlane/Fastfile
Labels: Ready for Testing
