Repository powerhome/playbook-swift, pull requests merged in 2025-01, with the labels that each got.

#482 [PBIOS-656] Typeahead presentation fix
  Sources/Playbook/Components/Fixed Confirmation Toast/PBToast.swift
  Sources/Playbook/Components/Popover/PBPopover.swift
  Sources/Playbook/Components/Popover/Popover+Position.swift
  Sources/Playbook/Components/Popover/PopoverManager.swift
  Sources/Playbook/Components/Progress Step/PBProgressStep.swift
  Sources/Playbook/Components/Select/PBSelect.swift
  Sources/Playbook/Components/Selectable Card/PBSelectableCard.swift
  Sources/Playbook/Components/Text Area/PBTextArea.swift
  Sources/Playbook/Components/Tooltip/PBTooltip.swift
  Sources/Playbook/Components/Typeahead/GridInputField.swift
  Sources/Playbook/Components/Typeahead/PBTypeahead.swift
  Sources/Playbook/Components/Typeahead/PBTypeaheadTemplate.swift
  Sources/Playbook/Components/Typeahead/Pill/TypeaheadPill.swift
  Sources/Playbook/Components/Typeahead/Typeahead.swift
  Sources/Playbook/Components/Typeahead/TypeaheadCatalog.swift
  Sources/Playbook/Resources/Extensions/OnChange+Debounce.swift
  Sources/Playbook/Resources/Extensions/OnScrollDetection.swift
  Sources/Playbook/Resources/Extensions/View+Reader.swift
  Sources/Playbook/Resources/Helper Files/Mocks.swift
Labels: Ready for Testing

#459 [PBIOS-569] Typeahead section list
  Sources/Playbook/Components/Typeahead/Typeahead.swift
Labels: Ready for Testing

#484 [PBIOS-659] Update PBSelect Kit Dynamic Select
  Sources/Playbook/Components/Select/PBSelect.swift
  Sources/Playbook/Components/Select/SelectCatalog.swift
Labels: enhancement, improvement, Ready for Testing

#480 [PBIOS-655] pbIcon Clipping Fix
  Sources/Playbook/Components/Icon/PBIcon.swift
Labels: bug, Ready for Testing

#486 [PBIOS-668] Section list fix for connect
  Sources/Playbook/Components/Popover/PopoverCatalog.swift
  Sources/Playbook/Components/Popover/PopoverExploration.swift
  Sources/Playbook/Components/Typeahead/PBTypeaheadTemplate.swift
  Sources/Playbook/Components/Typeahead/Typeahead.swift
  Sources/Playbook/Resources/Helper Files/Mocks.swift
Labels: Ready for Testing

#490 [PBIOS-671] Fix Reaction Button Font Color Alignment
  Sources/Playbook/Components/Button/ButtonsCatalog.swift
  Sources/Playbook/Components/Button/PBReactionButton.swift
Labels: bug, Ready for Testing

#492 [PBIOS-672] 6.6.3-release
  Changelog.md
  PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj
  project.yml
Labels: Ready for Testing

#491 [RANGR-878] Update to profile managed by iOS provisiong profile repository
  Gemfile
  Gemfile.lock
  PlaybookShowcase/PlaybookShowcase.xcodeproj/project.pbxproj
Labels: Ready for Testing
